language: python
python:
    - "2.7"
    - "3.4"
# command to install dependencies
install:
    - "pip install should"
    - "pip install coveralls"
# command to run tests
script: make cov

after_success:
    coveralls
